export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const REQUEST_PRODUCTS_FAILURE = 'REQUEST_PRODUCTS_FAILURE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const SUBTRACT_FROM_CART = 'SUBTRACT_FROM_CART';
